name: 'setup plank'
description: 'Composite action to install planck (no-op if invoked for Windows)'
inputs:
  shell:
    description: 'shell must be specified for composite actions - so we setup an appropriate default'
    required: false
    default: ${{ contains(runner.os, 'windows') && 'pwsh' || 'bash' }}

runs:
  using: 'composite'

  steps:
    - name: Install planck (macOS)
      shell: ${{ inputs.shell }}
      run: brew install planck
      if: runner.os == 'macOS'

    - name: Install planck (linux)
      shell: ${{ inputs.shell }}
      run: |
        # There are not planck binaries for jammy yet, so hack-around to use focal release
        sudo add-apt-repository -y "deb http://cz.archive.ubuntu.com/ubuntu focal main universe"
        sudo add-apt-repository -y "deb http://security.ubuntu.com/ubuntu focal-security main"

        # is missing after installing planck so compensate
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y libicu66

        wget https://launchpad.net/~mfikes/+archive/ubuntu/planck/+files/planck_2.25.0-1ppa1~focal1_amd64.deb
          sudo apt-get install ./planck_2.25.0-1ppa1~focal1_amd64.deb
      if: runner.os == 'Linux'

    - name: Planck version (macos, linux)
      shell: ${{ inputs.shell }}
      run: |
        echo "planck --version"
        planck --version
      if: runner.os != 'Windows'
