name: 'shared setup'
description: 'Composite action for common setup steps'
inputs:
  jdk:
    description: 'jdk major version, use value skip to not install jdk'
    required: false
    default: '11'
  shell:
    description: 'shell must be specified for composite actions - so we setup an appropriate default'
    required: false
    default: ${{ contains(runner.os, 'windows') && 'pwsh' || 'bash' }}
  clj-cache-prefix:
    description: 'cache key prefix'
    required: false
    default: clj-deps
  clj-cache-hash-files:
    description: 'base cache hash on these files'
    required: false
    default: "'deps.edn','bb.edn'"

runs:
  using: 'composite'

  steps:
    - name: Clojure deps cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.deps.clj
          ~/.gitlibs
        key: ${{ runner.os }}-${{ inputs.clj-cache-prefix }}-${{ hashFiles(inputs.clj-cache-hash-files) }}
        restore-keys: ${{ runner.os }}-${{ inputs.clj-cache-prefix }}

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.jdk }}
      if: inputs.jdk != 'skip'

    - name: Install Babashka & Clojure
      uses: DeLaGuardo/setup-clojure@13.0
      with:
        bb: 'latest'
        cli: 'latest'

    - name: Tools Versions
      shell: ${{ inputs.shell }}
      run: |
        echo "java -version"
        java -version
        echo "bb --version"
        bb --version
        echo "clojure --version"
        clojure --version

    - name: Download Clojure Dependencies
      shell: ${{ inputs.shell }}
      run: bb download-deps
