name: Native Image Tests

on:
  # allow this workflow to be called from other workflows, namely: publish
  workflow_call:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      tests: ${{ setps.set-tests.outputs.tests }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/workflows/shared-setup

      - id: set-tests
        name: Set test var for matrix
        # run ci_native_tests.clj directly instead of via bb task to avoid generic task output
        run: echo "tests=$(bb script/ci_native_tests.clj matrix-for-ci --format=json)" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.setup.outputs.tests) }}

    name: ${{ matrix.desc }}

    steps:
      #
      # Tell git not to convert newlines on checkout for Windows
      #
      - name: Prepare git (Windows)
        run: git config --global core.autocrlf false
        if: matrix.os == 'windows'

      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Setup
        uses: ./.github/workflows/shared-setup
        with:
          jdk: skip

      - name: Install GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      #
      # native image tests
      #
      - name: Run Tests
        run: ${{ matrix.cmd }}
